### ISSUE TITLE
Mod insta-crashes dedi-servers on 1.20.1

### ISSUE THREAD

**Issue by Epik-B0mber** [roberttkahelin8/thingmajigs#6]
I went through a lengthy experiment and isolated this mod as the core issue of a crash I was having. Don't know what causes it it just immediately flops if enabled. 
I suck with coding so I'm pretty sure this is the error code for it. Hope this helps or sum.
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.43-universal.jar%23166!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.1.43-universal.jar%23166!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23161!/:?] {re:classloading}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.43.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.43.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by roberttkahelin8** [comment]
Could I have the full log for this error? This only seems to be part of the whole thing.
I need more info so I can look at my stuff to see what class could be causing the issue. This seems to be an error log for the loader itself...

**Comment by roberttkahelin8** [comment]
If you look in the repository, you'll see a server fix version of 1.6.4 Thingamajigs (an upcoming release for the mod).
Try that and report any more issues. (Test the server by placing the mod's signs a bunch and typing text on them).

**Comment by roberttkahelin8** [comment]
[everyone] I have confirmed that the default Minecraft server jar runs with forge and my mod now with the fixed version of the mod, and that the blocks effected by this change don't seem to crash the client or server so far, and the world saves as well.
Need more servers to test this.

**Comment by roberttkahelin8** [comment]
If someone has another bug like this, make a new bug report.
